# working directory (will include links to raw data, logs, results)
workdir: "/mnt/data/sbusi/rashi_MG"

# internal databases, i.e. created by the pipeline (external databases should be defined elsewhere)
dbsdir: "/mnt/data/sbusi/rashi_MG"

# samples: unique sample ID and R1/R2 FASTQ files (absolute paths)
samples: "config/samples_metadata.tsv"

# primer sequences
primer:
  forward: "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG"
  forward_revcompl: "CTGCWGCCNCCCGTAGGCTGTCTCTTATACACATCTGACGCTGCCGACGA"
  reverse: "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC"
  reverse_revcompl: "GGATTAGATACCCBDGTAGTCCTGTCTCTTATACACATCTCCGAGCCCACGAGAC"

# adapter sequences (to be adjusted as needed)
adapter:
  forward1: "TACACTCTTTCCCTACACGACGCTCTTCCGATCT"
  revcompl1: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA"
  forward2: "AGATCGGAAGAG"
  revcompl2: "CTCTTCCGATCT"

# https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
fastqc:
  threads: 2

# https://cutadapt.readthedocs.io/en/stable/
cutadapt:
  threads: 10
  strategy: "TruSeq" # how to perform adapter trimming and filtering
  adapters:
    # From (document # 1000000002694, v15, February 2021)
    # https://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences-1000000002694-15.pdf
    # p28-29: Sequences for TruSeq Kits: Adapter Trimming
    forward: "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    reverse: "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
  # additional params
  # min. length; trim Ns; 3' quality trimming
  params: "--minimum-length 100 --trim-n --quality-cutoff 20"

#KRAKEN2
kraken2:
  db: "/mnt/esb-storage-01/NOMIS/maxikraken2_1903_140GB/"
  threads: 8
