# working directory (will include links to raw data, logs, results)
workdir: "/mnt/data/sbusi/vip"

# internal databases, i.e. created by the pipeline (external databases should be defined elsewhere)
dbsdir: "/mnt/data/sbusi/vip"

# samples: unique sample ID and R1/R2 FASTQ files (absolute paths)
samples: "config/samples.tsv"

# primer sequences
primer:
  forward: "TCGTCGGCAGCGTCAGATGTGTATAAGAGACAGCCTACGGGNGGCWGCAG"
  forward_revcompl: "CTGCWGCCNCCCGTAGGCTGTCTCTTATACACATCTGACGCTGCCGACGA"
  reverse: "GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAGGACTACHVGGGTATCTAATCC"
  reverse_revcompl: "GGATTAGATACCCBDGTAGTCCTGTCTCTTATACACATCTCCGAGCCCACGAGAC"

# adapter sequences
adapter:
  forward1: "AGATCGGAAGAG"
  forward2: "TGGAATTCTCGG"
  revcompl1: "CTCTTCCGATCT"
  revcompl2: "CCGAGAATTCCA"

# https://www.bioinformatics.babraham.ac.uk/projects/fastqc/
fastqc:
  threads: 2

# https://cutadapt.readthedocs.io/en/stable/
cutadapt:
  threads: 2

# https://www.bioconductor.org/packages/release/bioc/html/dada2.html
dada2:
  # fastq:
  #   threads: 5
  #   truncLen: [0, 287]
  #   minLen: 275
  asv:
    threads_single: 3
    threads: 15
    pool: true # TRUE or pseudo  # TODO
    minOverlap: 31  # see wiki for details
    # https://zenodo.org/record/1172783#.XlZ__CmYXMJ (SILVA v.132)
    tax: "https://zenodo.org/record/1172783/files/silva_nr_v132_train_set.fa.gz"
